
spring:
  freemarker:
    check-template-location: false
  activiti:
    check-process-definitions: false
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
    open-in-view: true
    generate-ddl: false
  liquibase:
    enabled: false
    change-log: classpath:META-INF/liquibase/activiti-app-db-changelog.xml
  aop:
    proxy-target-class: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workflow2?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
server:
  port: 8080
  servlet:
    context-path: "/wf"
management:
  endpoints:
    web:
      exposure:
        include: "*"

